{% set version = "0.20.0" %}

package:
  name: azure-mgmt-common
  version: {{ version }}

source:
  fn: azure-mgmt-common{{ version }}.zip
  url: https://pypi.org/packages/source/a/azure-mgmt-common/azure-mgmt-common-{{ version }}.zip
  md5: f82f47f476964140576576734436ba4d
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - requests
    - azure-common
    - azure-mgmt-nspkg
  run:
    - python >={{ python_min }}
    - requests
    - azure-common
    - azure-mgmt-nspkg

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.common
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Resource Management Client Library for Python (Common)'

extra:
  recipe-maintainers:
    - Maxyme
