travis:
  secure:
    BINSTAR_TOKEN: YXqgbnNDrYcl4cnSS3bY2xDm31jAwAFbR9+zkyjndWLjlOT2HkDpT5T5tb1Z5rnpuc8ruuXVeFPdhZvqya0aCDXAl7NNuOoDKEYOlhYTBUT1thup9A2G2jLNTctnKyJPlaXDQWWMiv/SXGdGx6VJWgDY7UddIFLNzmnGFuta8WPVfnKHdHB/tOS9t2yb/RYPpczJ7kkmmP9qaSgxw0LV37QTTuo5gxeE5Xl1oQ+VcnQQxZM+AkcLYbYSssNZONf00oETSDtb8M8tZ/D1qiiL/1qTR70Btf1ft2npuv6fKVXSw6QCvqGHk6NfNEUd9UKl1aHBaYiaq2xqJ7Y/Nrq1zaUfIeRlm7k7120h1g58j4I2erwsjuECOiEJj/wJLQ/9b6b1lYIJLjvnPGZ3Kb8PyTX1TWv23mkTUAAgy8ltZHUm1Q2IUOghQGj/knD0N7/Bxa6EFXd6VwnNZv+ZPt/Yde9eyTD4upIKV7LmcobQRHCXY4nyWyetpywJnkWXS7SdALtQgfsLqe5IIv7fZpF/8cthdqmKbUPOekaPVjMrMEWxJ5EnvVm59VJ2MY1iTJyn3QfQjZTZnsfRVjKmngFOFchPFjD/duiGJDP5mDs45ydlHil4qxeH0nmyQxDKwLPON42+WmZNDyZDcon3OiutSsbwPVFC6FSMM/pcwt/SGOU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
